// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	gql_bigint "github.com/xplorfin/gql-bigint"
)

type BigIntObject struct {
	Value gql_bigint.BigInt `json:"value"`
}

type BigUIntObject struct {
	Value gql_bigint.BigUInt `json:"value"`
}
