name: Renew Documentation

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  main:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@master