name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci nochecks]') }}
    strategy:
      matrix:
        go-version:
          - 1.16.x
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go modules cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          skip-pkg-cache: true