name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci nochecks]') }}
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci-test